apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/kube-vip/kube-vip-cloud-provider
    targetRevision: v0.0.10
    path: manifest
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
