apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-discovery
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: istio-system
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://istio-release.storage.googleapis.com/charts
      targetRevision: 1.23.2
      chart: istiod
      helm:
        valueFiles:
          - $values/argocd-apps/helm-values/istio-discovery-values.yaml
    - repoURL: http://gitea-http.gitea:3000/nguyenminh-phuc/k8s-homeserver
      targetRevision: custom-v3
      ref: values
  project: default
  syncPolicy:
    automated:
      prune: true
