apiVersion: v1
kind: Namespace
metadata:
  name: homeserver
  labels:
    homeserver-gateway: enabled
    istio-injection: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: homeserver
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/nguyenminh-phuc/k8s-homeserver
    targetRevision: custom-v3
    path: argocd-apps-lw
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
