apiVersion: v1
kind: Namespace
metadata:
  name: gitea
  labels:
    homeserver-gateway: enabled
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: gitea
    server: https://kubernetes.default.svc
  source:
    repoURL: https://dl.gitea.com/charts/
    targetRevision: 10.4.1
    chart: gitea
    helm:
      valuesObject:
        ingress:
          hosts:
            - host: git.phuc.localcert.net
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql-ha:
          enabled: false
        postgresql:
          enabled: true
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
